/* tslint:disable */

/**
 * This file was automatically generated by "Swaxios".
 * It should not be modified by hand.
 */

import {AxiosInstance, AxiosRequestConfig} from 'axios';

export class LoginService {
  private readonly apiClient: AxiosInstance;

  constructor(apiClient: AxiosInstance) {
    this.apiClient = apiClient;
  }

  /**
   * @param username The user name for login
   * @param password The password for login in clear text
   */
  loginUser = async (params?: {
    username: string;
    password: string;
  }): Promise<string> => {
    const config: AxiosRequestConfig = {
      method: 'get',
      params,
      url: '/user/login',
    };
    const response = await this.apiClient.request<string>(config);
    return response.data;
  };
}
