/* tslint:disable */

/**
 * This file was automatically generated by "Swaxios".
 * It should not be modified by hand.
 */

import {AxiosInstance, AxiosRequestConfig} from 'axios';

export class LogoutService {
  private readonly apiClient: AxiosInstance;

  constructor(apiClient: AxiosInstance) {
    this.apiClient = apiClient;
  }

  logoutUser = async (): Promise<void> => {
    const config: AxiosRequestConfig = {
      method: 'get',
      url: '/user/logout',
    };
    await this.apiClient.request(config);
  };
}
