/* tslint:disable */

/**
 * This file was automatically generated by "Swaxios".
 * It should not be modified by hand.
 */

import {AxiosInstance, AxiosRequestConfig} from 'axios';

export class InventoryService {
  private readonly apiClient: AxiosInstance;

  constructor(apiClient: AxiosInstance) {
    this.apiClient = apiClient;
  }

  getInventory = async (): Promise<{}> => {
    const config: AxiosRequestConfig = {
      method: 'get',
      url: '/store/inventory',
    };
    const response = await this.apiClient.request<{}>(config);
    return response.data;
  };
}
