/* tslint:disable */

/**
 * This file was automatically generated by "Swaxios".
 * It should not be modified by hand.
 */

import {AxiosInstance, AxiosRequestConfig} from 'axios';
import {Order} from '../../interfaces/';

export class OrderService {
  private readonly apiClient: AxiosInstance;

  constructor(apiClient: AxiosInstance) {
    this.apiClient = apiClient;
  }

  /**
   * @param body order placed for purchasing the pet
   */
  placeOrder = async (body: Order): Promise<Order> => {
    const config: AxiosRequestConfig = {
      data: {
        ...body,
      },
      method: 'post',
      url: '/store/order',
    };
    const response = await this.apiClient.request<Order>(config);
    return response.data;
  };

  /**
   * @param orderId ID of pet that needs to be fetched
   */
  getOrderById = async (orderId: number): Promise<Order> => {
    const config: AxiosRequestConfig = {
      method: 'get',
      url: `/store/order/${orderId}`,
    };
    const response = await this.apiClient.request<Order>(config);
    return response.data;
  };

  /**
   * @param orderId ID of the order that needs to be deleted
   */
  deleteOrder = async (orderId: number): Promise<void> => {
    const config: AxiosRequestConfig = {
      method: 'delete',
      url: `/store/order/${orderId}`,
    };
    await this.apiClient.request(config);
  };
}
