/* tslint:disable */

/**
 * This file was automatically generated by "Swaxios".
 * It should not be modified by hand.
 */

import {AxiosInstance, AxiosRequestConfig} from 'axios';
import {Pet} from '../../interfaces/';

export class FindByStatusService {
  private readonly apiClient: AxiosInstance;

  constructor(apiClient: AxiosInstance) {
    this.apiClient = apiClient;
  }

  /**
   * @param status Status values that need to be considered for filter
   */
  findPetsByStatus = async (params?: {status: {}}): Promise<Array<Pet>> => {
    const config: AxiosRequestConfig = {
      method: 'get',
      params,
      url: '/pet/findByStatus',
    };
    const response = await this.apiClient.request<Array<Pet>>(config);
    return response.data;
  };
}
