/* tslint:disable */

/**
 * This file was automatically generated by "Swaxios".
 * It should not be modified by hand.
 */

import {AxiosInstance, AxiosRequestConfig} from 'axios';
import {ApiResponse} from '../../interfaces/';

export class UploadImageService {
  private readonly apiClient: AxiosInstance;

  constructor(apiClient: AxiosInstance) {
    this.apiClient = apiClient;
  }

  /**
   * @param petId ID of pet to update
   * @param additionalMetadata Additional data to pass to server
   * @param file file to upload
   */
  uploadFile = async (petId: number): Promise<ApiResponse> => {
    const config: AxiosRequestConfig = {
      method: 'post',
      url: `/pet/${petId}/uploadImage`,
    };
    const response = await this.apiClient.request<ApiResponse>(config);
    return response.data;
  };
}
